import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType } from 'docx';
import PDFDocument from 'pdfkit';

const s=v=>String(v??'');
function sections(p){return [
 ['Executive Communication',p.executive_communication],['Executive Summary',p.executive_summary],['Proposed Solution Overview',rowsText(p.solution_matrix)],['Detailed Proposed Solution',p.detailed_solution],['Implementation Plan',rowsText(p.implementation_plan)],['Implementation Assumptions',p.assumptions],['Training & Handover',p.training_handover],['After Sales Support',p.after_sales_support],['Conclusion',p.conclusion],['Priced Bill of Quantity',rowsText(p.boq)],['Optional Items',rowsText(p.optional_items)],['Grand Total',`${p.grand_total||''} ${p.currency||''}`],['Terms and Conditions',p.terms_conditions]
]}
function rowsText(rows){return Array.isArray(rows)?rows.map(r=>Object.values(r).join(' | ')).join('\n'):''}
function makeDoc(p){const children=[new Paragraph({text:'Commercial Proposal',heading:HeadingLevel.TITLE}),new Paragraph({text:s(p.project)}),new Paragraph({text:`Prepared for: ${s(p.client)} | Prepared by: ${s(p.prepared)} | Date: ${s(p.date)} | Ref: ${s(p.reference)} | Version: ${s(p.version)}`})]; for(const [h,t] of sections(p)){children.push(new Paragraph({text:h,heading:HeadingLevel.HEADING_1})); for(const line of s(t).split('\n'))children.push(new Paragraph({text:line}))} return new Document({sections:[{children}]});}
function makePdf(p){return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:48});const chunks=[];doc.on('data',x=>chunks.push(x));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);doc.fontSize(20).text('Commercial Proposal',{align:'center'}).moveDown().fontSize(13).text(s(p.project),{align:'center'}).moveDown();doc.fontSize(9).text(`Prepared for: ${s(p.client)}\nPrepared by: ${s(p.prepared)}\nDate: ${s(p.date)}  Ref: ${s(p.reference)}  Version: ${s(p.version)}`).moveDown(2);for(const [h,t] of sections(p)){doc.fontSize(13).text(h).moveDown(.3);doc.fontSize(9).text(s(t),{lineGap:2}).moveDown(1);if(doc.y>720)doc.addPage()}doc.end()})}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).end();try{const {type,proposal}=req.body||{};if(!proposal)throw new Error('Proposal missing');if(type==='docx'){const b=await Packer.toBuffer(makeDoc(proposal));res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.wordprocessingml.document');res.setHeader('Content-Disposition','attachment; filename="Commercial_Proposal.docx"');return res.status(200).send(b)}if(type==='pdf'){const b=await makePdf(proposal);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="Commercial_Proposal.pdf"');return res.status(200).send(b)}throw new Error('Invalid export type')}catch(e){return res.status(500).json({error:e.message||String(e)})}}
